### ISSUE TITLE
Path formatting bug

### ISSUE THREAD

**Issue by markoprodanovic** [saud-learning-services/canvas-peer-reviews#23]
![image](https://user-images.githubusercontent.com/22332030/108428955-35975080-71f4-11eb-9da5-909702c2a553.png)

discovered by Donal on Feb 12th

likely to do with explicit filepaths with forward slash ('/')

**Comment by markoprodanovic** [comment]
Resolved

**Comment by alisonmyers** [comment]
Was this due to the explicit forward slash or the datetime stamp in the file name ?

**Comment by markoprodanovic** [comment]
Both. Explicit forward slash caused issues on windows -- and I found out that windows also doesn't like ":" in filenames
